version: '2'

services:
  mysqldb:
    container_name: ddd-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
#      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3307:3306'
    volumes:
      - './datadir:/var/lib/mysql'
  myapp:
    container_name: ddd-app
    image: wyveo/nginx-php-fpm:php81
    ports:
      - '8000:80'
    environment:
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=todolist
    volumes:
      - './:/docker-compose/webapp'
      - './ddd-app.conf:/etc/nginx/conf.d/ddd-app.conf'
    depends_on:
      - mysqldb
